import CardComponent from "./CardComponent";

function LessonsComponent(){

    const wordsToLearn1 = {
        words: [
        {eng: 'Humidity',
        ukr: 'Вологість'},
        {eng: 'Humid',
        ukr: 'Вологий, сирий'},
        {eng: 'Stuffy',
        ukr: 'Душний, задушливий'},
        {eng: 'Feature',
        ukr: 'Особливість, риса'},
        {eng: 'To master',
        ukr: 'Опановувати'},
        {eng: 'Let down',
        ukr: 'Підводити, розчаровувати'},
        {eng: 'Tendency',
        ukr: 'Тендеція, схильність'},
        {eng: 'Up-and-coming',
        ukr: 'Багатообіцяючий, перспективний'},
        {eng: 'Neglect',
        ukr: 'Зневажати, нехтувати'},
        {eng: 'Negligence',
        ukr: 'Недбалість, халатність'},
        {eng: 'Lenient',
        ukr: 'М\'який, поблажливий'},
        {eng: 'Show off',
        ukr: 'Випендрюватися'},
        {eng: 'Picky',
        ukr: 'Прискіпливий'},
        {eng: 'Solve',
        ukr: 'Вирішувати (проблему, задачу)'},
        {eng: 'Resentment',
        ukr: 'Обурення, образа'},
        {eng: 'Resentful',
        ukr: 'Ображений, обурений'},
        {eng: 'On the safe side',
        ukr: 'Про всяк випадок'},
        {eng: 'Resent',
        ukr: 'Обурюватися, ображатися'},
        {eng: 'Dean',
        ukr: 'Декан, настоятель собору'},
        {eng: 'Callous',
        ukr: 'Черствий, безсердечний'},
        {eng: 'To bribe',
        ukr: 'Давати хабар'},
        {eng: 'Bribery',
        ukr: 'Хабарництво, продажність'},
        {eng: 'Restrict',
        ukr: 'Обмежувати'},
        {eng: 'Strict',
        ukr: 'Суворий, вимогливий'},
        {eng: 'Hypocrite',
        ukr: 'Лицемір'},
        {eng: 'Spit',
        ukr: 'Плювати'},
        {eng: 'Footage',
        ukr: 'Метраж, кадри'},
        {eng: 'Heritage',
        ukr: 'Спадщина, спадок'},
        {eng: 'Inherit',
        ukr: 'Успадковувати'},
        {eng: 'Goldsmith',
        ukr: 'Ювелір'},
        {eng: 'Insription',
        ukr: 'Напис'},
        {eng: 'Tie',
        ukr: 'Краватка, зав\'язвувати'},
        {eng: 'Untie',
        ukr: 'Розв\'язувати'},
        {eng: 'Flame',
        ukr: 'Полум\'я'},
        {eng: 'Inflammation',
        ukr: 'Запалення'}
      ],
      lesson: 1};

      const wordsToLearn2 = {
        words: [
        {eng: 'Brew',
        ukr: 'Заварювати'},
        {eng: 'Lace',
        ukr: 'Мереживо, шнурок'},
        {eng: 'Bootlace',
        ukr: 'Шнурок'},
        {eng: 'Collar',
        ukr: 'Комір'},
        {eng: 'Sleeve',
        ukr: 'Рукав'},
        {eng: 'Psyche',
        ukr: 'Психіка'},
        {eng: 'Remorse',
        ukr: 'Каяття, муки сумління'},
        {eng: 'Flatter',
        ukr: 'Підлещуватися'},
        {eng: 'Abundant',
        ukr: 'Рясний, багатий'},
        {eng: 'Decoy',
        ukr: 'Приманка, пастка'},
        {eng: 'Insecurity',
        ukr: 'Невпевненість'},
        {eng: 'Inferirority complex',
        ukr: 'Комплекс неповноцінності'},
        {eng: 'Inmate',
        ukr: 'В\'язень'},
        {eng: 'Immerse',
        ukr: 'Занурювати, поринути'},
        {eng: 'Deprive of',
        ukr: 'Позбавляти, відбирати'},
        {eng: 'To great extent',
        ukr: 'Значною мірою'},
        {eng: 'To some extent',
        ukr: 'Певною мірою'},
        {eng: 'Exceed',
        ukr: 'Перевищувати'},
        {eng: 'Excess',
        ukr: 'Надлишок'},
        {eng: 'Sue',
        ukr: 'Подавати в суд'},
        {eng: 'Lawsuit',
        ukr: 'Судовий процес'},
        {eng: 'Fine',
        ukr: 'Штраф, штрафувати'},
        {eng: 'Violate',
        ukr: 'Порушувати'},
        {eng: 'Fare',
        ukr: 'Плата за проїзд'},
        {eng: 'Entrance',
        ukr: 'Вхід'},
        {eng: 'Treat',
        ukr: 'Лікувати'},
        {eng: 'Freak Out',
        ukr: 'Психувати'},
        {eng: 'Ram',
        ukr: 'Таранити'},
        {eng: 'Biased',
        ukr: 'Упереджений'},
        {eng: 'Intentionally',
        ukr: 'Навмисно'},
        {eng: 'Deleberately',
        ukr: 'Навмисно'},
        {eng: 'By chance',
        ukr: 'Випадково'},
        {eng: 'Accidentally',
        ukr: 'Випадково'},
        {eng: 'Blow over',
        ukr: 'Минати, проходити'},
        {eng: 'Inequality',
        ukr: 'Нерівність'},
        {eng: 'Minor',
        ukr: 'Незначний'},
        {eng: 'Major',
        ukr: 'Основний'},
        {eng: 'Riot',
        ukr: 'Бунт, повстання'},
        {eng: 'Rebellion',
        ukr: 'Повстання'},
        {eng: 'Fulfil',
        ukr: 'Виконувати'},
        {eng: 'Carry out',
        ukr: 'Виконувати'},
      ],
      lesson:2};

      const wordsToLearn3 = {
        words: [
        {eng: 'Harvest',
        ukr: 'Врожай'},
        {eng: 'Pole',
        ukr: 'Стовб'},
        {eng: 'Chase',
        ukr: 'Переслідувати'},
        {eng: 'Persue',
        ukr: 'Переслідувати'},
        {eng: 'Get on with',
        ukr: 'Ладити'},
        {eng: 'Superficial',
        ukr: 'Поверхневий'},
        {eng: 'Lag behind',
        ukr: 'Відставати'},
        {eng: 'Fall behind',
        ukr: 'Відставати'},
        {eng: 'Deceive',
        ukr: 'Обманювати'},
        {eng: 'Deception',
        ukr: 'Обман, шахрайство'},
        {eng: 'Treason',
        ukr: 'Зрада, '},
        {eng: 'Betreyal',
        ukr: 'Зрада'},
        {eng: 'Landlord',
        ukr: 'Домовласник'},
        {eng: 'Tenant',
        ukr: 'Орендатор, житель'},
        {eng: 'Public utilities',
        ukr: 'Комунальні послуги'},
        {eng: 'Receipt',
        ukr: 'Чек, квитанція'},
        {eng: 'Electrician',
        ukr: 'Електрик'},
        {eng: 'Plumber',
        ukr: 'Сантехник'},
        {eng: 'Tub',
        ukr: 'Ванна'},
        {eng: 'Bath tub',
        ukr: 'Ванна'},
        {eng: 'Faucet',
        ukr: 'Кран'},
        {eng: 'Tap',
        ukr: 'Кран'},
        {eng: 'Leak',
        ukr: 'Витік, протікати'},
        {eng: 'Lavatory pan',
        ukr: 'Унітаз'},
        {eng: 'Lid',
        ukr: 'Кришка'},
        {eng: 'Casserole',
        ukr: 'Кастрюля'},
        {eng: 'Sause pan',
        ukr: 'Кастрюля'},
        {eng: 'Wash sink',
        ukr: 'Раковина'},
        {eng: 'Cabinets',
        ukr: 'Кухонні шкафчики'},
        {eng: 'Drapes',
        ukr: 'Штори'},
        {eng: 'Curtains',
        ukr: 'Штори'},
        {eng: 'Heating',
        ukr: 'Обігрів'},
        {eng: 'Radiator',
        ukr: 'Батарея, радіатор'},
        {eng: 'Window sill',
        ukr: 'Підвіконня'},
        {eng: 'Prop',
        ukr: 'Підпирати'},
        {eng: 'Crack',
        ukr: 'Тріщина'},
        {eng: 'Rug',
        ukr: 'Килимок'},
        {eng: 'Tissue',
        ukr: 'Паперова серветка'},
        {eng: 'Lining',
        ukr: 'Підкладка'},
        {eng: 'Padding',
        ukr: 'Набивка'},
        {eng: 'Rubber',
        ukr: 'Гума'},
        {eng: 'Balcony',
        ukr: 'Балкон'},
        {eng: 'Handrails',
        ukr: 'Перила, поручні'},
        {eng: 'Iron',
        ukr: 'Праска'},
        {eng: 'Sewing machine',
        ukr: 'Швейна машинка'},
        {eng: 'Wrap',
        ukr: 'Загортати'},
        {eng: 'Wrapping',
        ukr: 'Упаковка, обгортка'},
        {eng: 'Laundry',
        ukr: 'Пральня'},
        {eng: 'Oven',
        ukr: 'Піч, духовка'},
        {eng: 'Forfeit',
        ukr: 'Розплата, розплачуватися'},
        {eng: 'ATM',
        ukr: 'Банкомат'},
        {eng: 'Cash machine',
        ukr: 'Банкомат'},
        {eng: 'Real estate (agent)',
        ukr: 'Рієлтор'},
        {eng: 'Property agent',
        ukr: 'Агент з нерухомості'},
        {eng: 'Showdown',
        ukr: 'Протистояння'},
        {eng: 'Anticipate',
        ukr: 'Чекати, передбачити'},
        {eng: 'Foresee',
        ukr: 'Передбачити, знати наперед'},
      ],
      lesson:3}

    return(
        <div>
            <CardComponent words={wordsToLearn1}/>
            <CardComponent words={wordsToLearn2}/>
            <CardComponent words={wordsToLearn3}/>
        </div>
    );
}

export default LessonsComponent;